### ISSUE TITLE
Error importing single cycle waveforms

### ISSUE THREAD

**Issue by emiguevara** [JonathanTaquet/Oe2sSLE#19]
I'm getting constant errors when I try importing single cycle waveforms from the Elektron free sound packs:
https://www.elektron.se/soundpacks/immortal-waves/
https://www.elektron.se/soundpacks/oxford-overdrive/

The samples are loaded and edited in Oe2sSLE, and the program lets you save an `.all` file. But when trying to import the saved `.all` file, one exception is thrown for every sample. The file is corrupted and does not get imported by the Electribe 2 Sampler either.
 
I don't know anything about RIFF specifications unfortunately, this is the exception:

`/tmp/_MEIQfh0Qm/RIFF/__init__.py:252: UserWarning: 'RIFF' chunk contains an ignored truncaded chunk
/tmp/_MEIQfh0Qm/e2s_sample_all.py:491: UserWarning: Recovering from an error while reading a sample
Traceback (most recent call last):
  File "e2s_sample_all.py", line 487, in load
  File "e2s_sample_all.py", line 349, in __init__
  File "e2s_sample_all.py", line 362, in read
  File "RIFF/__init__.py", line 310, in __init__
  File "RIFF/__init__.py", line 333, in read
  File "RIFF/__init__.py", line 255, in read
AttributeError: type object 'ChunkList' has no attribute 'InvalidError'`

I have also tried using the Adventure Kid Waveforms, but they give no trouble. I attach an example `.all` file with some of the default samples, 10 AKWF correctly saved, and a problematic waveform from the Elektron Inmortal Waves package.
[e2sSample-MG1.zip](https://github.com/JonathanTaquet/Oe2sSLE/files/682149/e2sSample-MG1.zip)

**Comment by JonathanTaquet** [comment]
Ok, thank you.

I found the issue.

Elektron RIFF files use a non "usual" size for the format "fmt " chunk (they use 18 bytes instead of 16). Once I read that chunk I do not properly update its size (as internally I use only 16 bytes) before writing it.
I'll try to fix this soon.

**Comment by JonathanTaquet** [comment]
Ok, commit 49d471363c527c1ce2657a5e83462907da1c2efb should solve the issue.
Commit 71984db537cd0b5a34261011310642a0f9191f8c clean the 'fmt ' chunk before exporting it in a '.all' file. It seems to be not necessary, as electribe properly import '.all' file with 'fmt ' chunk containing extra data, but it mimics the result of an export from the electribe of a sample that had extra 'fmt ' data when imported.

**Comment by emiguevara** [comment]
Thanks a lot, will be testing later today. I think the "unusual" fmt sizes might be due to some audio editor writing more info (my bet is on Adobe Audition): exporting audio again with Audacity seems to give 16-byte fmts that we can normally read. By the way, I am still not sure, but I think the chunk can take up to 24 bytes.... see http://soundfile.sapp.org/doc/WaveFormat/

**Comment by emiguevara** [comment]
Tested last commits, works fine importing, manipulating and saving. Thanks again!

**Comment by JonathanTaquet** [comment]
Thank you for your report, it helps to make a stable application!
